apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalyst-app
    metrics: catalyst
  name: catalyst-app-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: app
    - port: 4080
      protocol: TCP
      name: metrics
  selector:
    app: catalyst-app
  type: ClusterIP
