{{- if .Values.cronjobs.enabled -}}
{{- $top := . -}}
{{- range $cronjob := .Values.cronjobs.jobs -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $cronjob.name }}"
  labels:
    app: catalyst-app
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ $top.Values.serviceAccount.name }}
          containers:
          - name: catalyst
            image: {{ $top.Values.image }}
            imagePullPolicy: IfNotPresent
            command: ["/opt/catalyst/bin/catalyst", "eval", "{{ $cronjob.command }}"]
            env:
            - name: REPLACE_OS_VARS
              value: "true"
            - name: ERLANG_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            volumeMounts:
              - name: config-volume
                mountPath: /etc/catalyst
          volumes:
            - name: config-volume
              projected:
                sources:
                - secret:
                    name: catalyst-config
                - configMap:
                    name: catalyst-app-config
---
{{- end }}
{{- end }}
