apiVersion: batch/v1
kind: CronJob
metadata:
  name: "error-summary"
  labels:
    app: catalyst-app
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: catalyst
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            command: ["/opt/catalyst/bin/catalyst", "eval", "Catalyst.ReleaseTasks.send_daily_summary()"]
            env:
            - name: REPLACE_OS_VARS
              value: "true"
            - name: ERLANG_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            volumeMounts:
              - name: config-volume
                mountPath: /etc/catalyst
          volumes:
            - name: config-volume
              projected:
                sources:
                - secret:
                    name: catalyst-config
                - configMap:
                    name: catalyst-app-config
