apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalyst-monitoring
  labels:
    release: metrics
spec:
  selector:
    matchLabels:
      metrics: catalyst
  endpoints:
  - port: metrics
    interval: 30s
