apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-app-deployment
  labels:
    app: catalyst-app
    {{- if .Values.ajAppMonitoring.enabled }}
    atomicjolt.com/release-notifier: enabled
    {{- end }}
  annotations:
    {{- if .Values.ajAppMonitoring.enabled }}
    {{- range $key, $value := .Values.ajAppMonitoring }}
    {{- if ne $key "enabled"}}
    atomicjolt.com/release-notifier-{{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  replicas: {{ .Values.appReplicaCount }}
  selector:
    matchLabels:
      app: catalyst-app
  template:
    metadata:
      labels:
        app: catalyst-app
{{ .Values.elasticsearchWhitelistLabels | toYaml | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: catalyst
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # helps with 0 downtime deploys
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "20"
        readinessProbe:
          httpGet:
            path: /health_check
            port: 8080
            scheme: HTTP
        env:
        - name: REPLACE_OS_VARS
          value: "true"
        - name: ERLANG_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/catalyst
        resources:
{{ .Values.appResources | toYaml | indent 10 }}
      initContainers:
      - name: check-migrations
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        command: ["/opt/catalyst/bin/catalyst", "eval", "Catalyst.ReleaseTasks.check_migrations(nil)"]
        env:
        - name: REPLACE_OS_VARS
          value: "true"
        - name: ERLANG_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/catalyst
      terminationGracePeriodSeconds: 60
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      volumes:
        - name: config-volume
          projected:
            sources:
            - secret:
                name: catalyst-config
            - configMap:
                name: catalyst-app-config
