apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        command: ["/opt/catalyst/bin/catalyst", "eval", "Catalyst.ReleaseTasks.migrate(nil)"]
        volumeMounts:
          - name: config-volume
            mountPath: /etc/catalyst
        env:
        - name: REPLACE_OS_VARS
          value: "true"
        - name: ERLANG_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
        - name: config-volume
          projected:
            sources:
            - secret:
                name: catalyst-config
            - configMap:
                name: catalyst-app-config
