apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-worker
  labels:
    app: catalyst-worker
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      app: catalyst-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: catalyst-worker
        cluster: catalyst-workers
{{ .Values.elasticsearchWhitelistLabels | toYaml | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: catalyst
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: REPLACE_OS_VARS
            value: "true"
          - name: ERLANG_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/catalyst
          - name: "shared-storage"
            mountPath: /shared
        resources:
{{ .Values.workerResources | toYaml | indent 10 }}
      {{- if and .Values.dnsSidecar.enabled .Values.dnsSidecar.metrics.enabled }}
      - name: unbound-exporter
        image: {{ .Values.dnsSidecar.metrics.image }}
        args:
        - --unbound.host=unix://{{ .Values.dnsSidecar.metrics.controlSocket }}
        ports:
        - name: metrics
          containerPort: {{ .Values.dnsSidecar.metrics.port }}
        volumeMounts:
        - name: unbound-socket
          mountPath: {{ .Values.dnsSidecar.metrics.controlSocket | dir }}
        {{- if .Values.dnsSidecar.metrics.resources }}
        resources:
{{ .Values.dnsSidecar.metrics.resources | toYaml | indent 10 }}
        {{- end }}
      {{- end }}
{{ if .Values.workerAffinity }}
      {{- with .Values.workerAffinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
{{ if .Values.workerNodeSelector }}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "{{ .Values.workerNodeSelector }}"
        effect: "NoSchedule"
      nodeSelector:
        type: "{{ .Values.workerNodeSelector }}"
{{ end }}
      initContainers:
      {{- if .Values.dnsSidecar.enabled }}
      - name: unbound
        image: {{ .Values.dnsSidecar.image }}
        restartPolicy: Always
        volumeMounts:
        - name: dns-config
          mountPath: /etc/unbound/unbound.conf
          subPath: unbound.conf
        {{- if .Values.dnsSidecar.metrics.enabled }}
        - name: unbound-socket
          mountPath: {{ .Values.dnsSidecar.metrics.controlSocket | dir }}
        {{- end }}
        {{- if .Values.dnsSidecar.resources }}
        resources:
{{ .Values.dnsSidecar.resources | toYaml | indent 10 }}
        {{- end }}
      {{- end }}
      - name: check-migrations
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        command: ["/opt/catalyst/bin/catalyst", "eval", "Catalyst.ReleaseTasks.check_migrations(nil)"]
        env:
        - name: REPLACE_OS_VARS
          value: "true"
        - name: ERLANG_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
          - name: config-volume
            mountPath: /etc/catalyst
      # Workers need to be given enough time to gracefully quit after finishing
      # current jobs
      terminationGracePeriodSeconds: 60
      {{- if .Values.dnsSidecar.enabled }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - "127.0.0.1"
        searches:
        - {{ .Release.Namespace }}.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        options:
        - name: ndots
          value: "2"
      {{- else }}
      dnsConfig:
        options:
        - name: ndots
          value: "2"
      {{- end }}
      volumes:
      - name: config-volume
        projected:
          sources:
          - secret:
              name: catalyst-config
          - configMap:
              name: catalyst-worker-config
      - name: "shared-storage"
        persistentVolumeClaim:
          claimName: "shared-storage"
      {{- if .Values.dnsSidecar.enabled }}
      - name: dns-config
        configMap:
          name: catalyst-worker-dns-config
      {{- end }}
      {{- if and .Values.dnsSidecar.enabled .Values.dnsSidecar.metrics.enabled }}
      - name: unbound-socket
        emptyDir: {}
      {{- end }}
