{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1" ) .Values.externalSecretRedis.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.extraSecretRedisConfigs }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecretRedis.spec.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecretRedis.spec.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecretRedis.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecretRedis.spec.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecretRedis.spec.target | nindent 4 }}
    name:  {{ .Values.redis.extraSecretRedisConfigs }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.extraSecretRedisConfigs }}-exporter
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecretRedis.spec.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecretRedis.spec.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecretRedis.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecretRedis.spec.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecretRedis.spec.target | nindent 4 }}
    name: {{ index .Values.redis.metrics.exporter.extraExporterEnvSecrets 0 }}
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: '{{ `{{- index . "redis.conf" | regexFind "(?m)^requirepass (.+)$" | replace "requirepass " "" -}}` }}'
{{- end }}
