{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" ) .Values.externalSecretRedis.enabled -}}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretRedis.name }}
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
{{- with .Values.externalSecretRedis.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
