apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-migrations
  labels:
    type: migrations
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        type: migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: rails
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "bundle exec rails db:migrate && bundle exec rails db:seed"]
          volumeMounts:
            - name: secrets
              mountPath: /app/config/k8s
            - name: credentials
              mountPath: /app/config/credentials
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.migrationConfigSecret | default .Values.configSecret }}
        - name: credentials
          secret:
            secretName: {{ .Values.credentialsSecret }}
