{{- if .Values.scheduledScaling.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "app.fullname" . }}-scaler
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - create
      - delete
      - update
      - patch
      - watch
      - list
      - get
{{- end }}
