apiVersion: v1
kind: Service
metadata:
  name: {{ include "aa-datatable-engine.fullname" . }}
  labels:
    {{- include "aa-datatable-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: node
      protocol: TCP
      name: http
  selector:
    {{- include "aa-datatable-engine.selectorLabels" . | nindent 4 }}
