apiVersion: v1
kind: Service
metadata:
  name: {{ include "canvas-rce-api.fullname" . }}
  labels:
    {{- include "canvas-rce-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9394
      targetPort: 9394
      protocol: TCP
      name: metrics
  selector:
    {{- include "canvas-rce-api.selectorLabels" . | nindent 4 }}
