{{- if and ( .Capabilities.APIVersions.Has "kubernetes-client.io/v1" ) .Values.externalSecret.enabled -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Values.configSecret }}
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
{{- with .Values.externalSecret.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
