{{- if .Values.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "canvas.fullname" . }}-worker
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "canvas.fullname" . }}-worker
{{- if .Values.worker.autoscaling.minReplicas }}
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
{{- end }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  {{- with .Values.worker.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.worker.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
