{{- if .Values.s3mail.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3mail.serviceAccountName" . }}
  labels:
    {{- include "canvas.labels" . | nindent 4 }}
  {{- with .Values.s3mail.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
