apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atomic-canvas.fullname" . }}-app
  labels:
    type: app-server
    {{- include "atomic-canvas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atomic-canvas.selectorLabels" . | nindent 6 }}
      type: app
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atomic-canvas.selectorLabels" . | nindent 8 }}
        type: app
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atomic-canvas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.app.terminationGracePeriodSeconds }}
      containers:
        - name: rails
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: shared
              mountPath: /shared
          ports:
            - name: rails
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8080
              scheme: HTTP
          env:
            {{- if .Values.metrics.prometheusExporter.enabled }}
            - name: STATSD_ENABLE
              value: "1"
            {{- end }}
          lifecycle:
            {{- toYaml .Values.app.lifecycle | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
        {{- if .Values.metrics.prometheusExporter.enabled }}
        - name: prometheus-exporter
          image: "{{ .Values.metrics.prometheusExporter.repository }}:{{ .Values.metrics.prometheusExporter.tag }}"
          imagePullPolicy: {{ .Values.metrics.prometheusExporter.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9394
            - name: listener
              containerPort: 8125
          args:
            - --statsd.listen-udp=:8125
            - --web.listen-address=:9394
            - --statsd.mapping-config=/statsd-exporter/mapping-config.yaml
          volumeMounts:
            - name: stats-exporter-mapping-config
              mountPath: /statsd-exporter/
              readOnly: true
          resources:
            {{- toYaml .Values.metrics.prometheusExporter.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.configSecret }}
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "atomic-canvas.fullname" . }}
        {{- if .Values.metrics.prometheusExporter.enabled }}
        - name: stats-exporter-mapping-config
          configMap:
            name: {{ include "atomic-canvas.fullname" . }}-exporter-config
            items:
            - key: exporterConfiguration
              path: mapping-config.yaml
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
