apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "atomic-canvas.fullname" . }}-migrations
  labels:
    type: migrations
    {{- include "atomic-canvas.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atomic-canvas.selectorLabels" . | nindent 8 }}
        type: migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: rails
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["bundle", "exec", "rake", "db:migrate"]
          volumeMounts:
            - name: secrets
              mountPath: /secrets
            - name: shared
              mountPath: /shared
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.configSecret }}
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "atomic-canvas.fullname" . }}
