apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "atomic-canvas.fullname" . }}
  labels:
    {{- include "atomic-canvas.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- with .Values.persistence.annotations  }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.persistence.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end -}}
  {{- with .Values.persistence.selectorLabels }}
  selector:
    matchLabels:
{{ toYaml . | indent 6 }}
  {{- end }}
