apiVersion: v1
kind: Service
metadata:
  name: {{ include "atomic-canvas.fullname" . }}-worker
  labels:
    {{- include "atomic-canvas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9394
      targetPort: 9394
      protocol: TCP
      name: metrics
  selector:
    {{- include "atomic-canvas.selectorLabels" . | nindent 4 }}
    type: worker
