scheduledScaling:
  # all times are UTC
  enabled: false
  image:
    repository: rancher/kubectl
    tag: v1.30.14
  cronjobs: []
    # - name: scale-up
    #   schedule: "0 11 * * 1-5"
    #   replicas: 2
    # - name: scale-down
    #   schedule: "0 23 * * 1-5"
    #   replicas: 1

service_monitor:
  enabled: true

cronjobs:
  enabled: false
  jobs:
  - name: error-summary
    schedule: "0 0 * * *"
    command: "Catalyst.ReleaseTasks.send_daily_summary()"

serviceAccount:
  create: false
  name: ""
  annotations: {}

persistence:
  size: 10Gi

ajAppMonitoring:
  enabled: false

redis:
  enabled: false
  #image.registry: public.ecr.aws/docker/library
  
  # Additional configuration (e.g. password)
  extraSecretRedisConfigs: redis-config

  useDeploymentWhenNonHA: true

  metrics:
    enabled: true
    exporter:
      extraExporterEnvSecrets:
        - redis-exporter

  serviceMonitor:
    enabled: true

  resources:
    requests:
      memory: 100Mi
    limits:
      memory: 200Mi

  redisConfig: |-
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    maxmemory-policy allkeys-lru
    save ""

externalSecrets:
  redis:
    enabled: false
    data: []
    # data:
    # - secretKey: redis.conf
    #   remoteRef:
    #     key: /path/redis.conf
    secretStoreRef: {}
    # secretStoreRef:
    #   name: aws-ssm
    #   kind: ClusterSecretStore
    refreshInterval: 2m
    dataFrom: []
    target: 
      creationPolicy: Orphan
      deletionPolicy: Retain
