{{- if and ( .Capabilities.APIVersions.Has "projectcalico.org/v3" ) .Values.networkPolicy.enabled -}}
{{- if .Capabilities.APIVersions.Has "projectcalico.org/v3/Tier" -}}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: {{ include "aa-datatable-engine.name" . }}
spec:
  tier: default
  selector: app.kubernetes.io/name == '{{ include "aa-datatable-engine.name" . }}'
  {{- if gt (len .Values.networkPolicy.ingressRules) 0 }}
  ingress:
    {{- range .Values.networkPolicy.ingressRules }}
    - {{ toYaml . | nindent 6}}
    {{- end }}
  {{- end }}
  egress:
    - action: Allow
      destination:
        services:
          name: kube-dns
          namespace: kube-system
    - action: Allow
      destination:
        services:
          name: {{ include "aa-datatable-engine.fullname" . }}-redis
          namespace: {{ .Release.Namespace }}
    {{- range .Values.networkPolicy.egressRules }}
    - {{ toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
