scheduledScaling:
  # all times are UTC
  enabled: false
  image:
    repository: bitnami/kubectl
    tag: 1.22
  cronjobs: []
    # - name: scale-up
    #   schedule: "0 11 * * 1-5"
    #   replicas: 2
    # - name: scale-down
    #   schedule: "0 23 * * 1-5"
    #   replicas: 1

redis:
  enabled: false
  architecture: standalone
  commonConfiguration: |-
    maxmemory 50mb
    save ""
  auth:
    sentinel: false
    existingSecret: redis
    existingSecretPasswordKey: redis-password
    usePasswordFiles: true
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi
  replica:
    replicaCount: 0
    disableCommands:
    persistence:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
