{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1" ) .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecrets.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecrets.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecrets.target | nindent 4 }}
    name:  {{ .Values.secretName }}
{{- end }}
