apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-worker
  labels:
    type: worker
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      type: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        type: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: rails
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["que", "--worker-count", "{{ .Values.rails.queWorkers }}", "./config/environment.rb"]
          volumeMounts:
            - name: secrets
              mountPath: /app/config/k8s
            {{- if .Values.persistence.enabled -}}
            - name: shared
              mountPath: /shared
            {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: check-migrations
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["rake", "db:abort_if_pending_migrations"]
          volumeMounts:
            - name: secrets
              mountPath: /app/config/k8s
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.rails.configSecret }}
        {{- if .Values.persistence.enabled -}}
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "app.fullname" . }}
        {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
