{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" ) .Values.externalSecrets.credentials.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-credentials
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecrets.credentials.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecrets.credentials.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecrets.credentials.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.credentials.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecrets.credentials.target | nindent 4 }}
    name:  {{ .Values.credentialsSecret }}
{{- end }}
