{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" ) .Values.externalSecrets.config.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecrets.config.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecrets.config.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecrets.config.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.config.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecrets.config.target | nindent 4 }}
    name:  {{ .Values.configSecret }}
{{- end }}
