# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
{{- if .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" . }}-app
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}-app
{{- if .Values.app.autoscaling.minReplicas }}
  minReplicas: {{ .Values.app.autoscaling.minReplicas }}
{{- end }}
  maxReplicas: {{ .Values.app.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    {{- if .Values.app.autoscaling.scaleUp.enabled }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.app.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.app.autoscaling.scaleUp.policies.percentValue }}
        periodSeconds: {{ .Values.app.autoscaling.scaleUp.policies.percentPeriodSeconds }}
      - type: Pods
        value: {{ .Values.app.autoscaling.scaleUp.policies.podsValue }}
        periodSeconds: {{ .Values.app.autoscaling.scaleUp.policies.podsPeriodSeconds }}
      selectPolicy: {{ .Values.app.autoscaling.scaleUp.selectPolicy }}
    {{- end }}
    {{- if .Values.app.autoscaling.scaleDown.enabled }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.app.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.app.autoscaling.scaleDown.policies.percentValue }}
        periodSeconds: {{ .Values.app.autoscaling.scaleDown.policies.percentPeriodSeconds }}
      - type: Pods
        value: {{ .Values.app.autoscaling.scaleDown.policies.podsValue }}
        periodSeconds: {{ .Values.app.autoscaling.scaleDown.policies.podsPeriodSeconds }}
      selectPolicy: {{ .Values.app.autoscaling.scaleDown.selectPolicy }}
    {{- end }}
{{- end }}
