{{- if .Values.scheduledScaling.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "app.fullname" . }}-scaler
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "app.fullname" . }}-scaler
subjects:
  - kind: ServiceAccount
    name: {{ template "app.fullname" . }}-scaler
    namespace: {{ .Release.Namespace }}
{{- end }}
