{{- if .Values.scheduledScaling.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.fullname" . }}-scaler
  labels:
    {{- include "app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
