{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-worker
  labels:
    {{- include "app.labels" . | nindent 4 }}
    type: metrics
spec:
  type: ClusterIP
  ports:
    - port: 9394
      targetPort: 9394
      protocol: TCP
      name: metrics
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    type: worker
{{- end }}
